name:                starship
version:             0.1.0.0
github:              "githubuser/starship"
license:             BSD3
author:              "Krzysztof Boleń"
maintainer:          "bolenk@student.mini.pw.edu.pl"
copyright:           "2021 Krzysztof Boleń"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/starship#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- gloss
- mtl
- random
- transformers
- dunai

ghc-options:
- -Wall
library:
  source-dirs: src

executables:
  starship-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - starship

tests:
  starship-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - starship
